version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    networks:
     - broker-kafka
    ports:
     - 192.168.57.73:2181:2181
     - 192.168.57.73:2888:2888
     - 192.168.57.73:3888:3888
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    networks:
     - broker-kafka
    ports:
     - 29092:29092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_LISTENERS= INTERNAL://kafka:9092, EXTERNAL://:29092
     - KAFKA_ADVERTISED_LISTENERS= INTERNAL://kafka:9092, EXTERNAL://192.168.57.73:29092
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
     - KAFKA_INTER_BROKER_LISTENER_NAME= INTERNAL

  mysql:
    image: quay.io/debezium/example-mysql:${DEBEZIUM_VERSION}
    ports:
     - 3306:3306
    networks:
     - broker-kafka
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    networks:
     - broker-kafka
    ports:
     - 192.168.57.73:8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
networks: 
  broker-kafka:
    driver: bridge
